In [1]:
import torch
from torch import nn

In [2]:
inputs=torch.tensor([[[0.2,.1,.3],[0.5,0.1,0.1]]])
B,S,E=inputs.size()
inputs=inputs.reshape(S,B,E)
inputs.size()

torch.Size([2, 1, 3])

In [4]:
parameter_shape=inputs.size()[-2:]
gamma=nn.Parameter(torch.ones(parameter_shape))
beta=nn.Parameter(torch.zeros(parameter_shape))

In [7]:
dims=[-(i+1) for i in range (len(parameter_shape))]

In [8]:
dims

[-1, -2]

In [9]:
mean=inputs.mean(dim=dims,keepdim=True)
mean.size()

torch.Size([2, 1, 1])

In [12]:
vars=((inputs - mean) **2).mean(dim=dims,keepdim=True)
epsilon=1e-5
std=(vars + epsilon).sqrt()
std

tensor([[[0.0817]],

        [[0.1886]]])

In [13]:
y=(inputs-mean)/std
y

tensor([[[ 0.0000, -1.2238,  1.2238]],

        [[ 1.4140, -0.7070, -0.7070]]])

In [14]:
out=gamma*y+beta

In [15]:
out

tensor([[[ 0.0000, -1.2238,  1.2238]],

        [[ 1.4140, -0.7070, -0.7070]]], grad_fn=<AddBackward0>)

In [35]:
import torch 
from torch import nn

class LayerNormalization():
    def __init__(self,parameters_shape,eps=1e-5):
        self.parameters_shape=parameters_shape
        self.eps=eps
        self.gamma=nn.Parameter(torch.ones(parameters_shape))
        self.beta=nn.Parameter(torch.zeros(parameters_shape))

    def forward(self,input):
        dims=[-(i+1) for i in range (len(self.parameters_shape))]
        mean=inputs.mean(dim=dims,keepdim=True)
        vars=((inputs - mean) **2).mean(dim=dims,keepdim=True)
        std=(vars + self.eps).sqrt()
        y=(inputs-mean)/std
        print(f"y \n : ({y.size()})=\n {y}")
        out=self.gamma * y+ self.beta
        print(f"out \n ({out.size()})=\n{out}")
        return out
        
        

In [36]:
batch_size=3
sentence_length=5
embedding_dim=8
inputs=torch.randn(sentence_length,batch_size,embedding_dim)
print(f"input \n({inputs.size()})=\n{inputs}")

input 
(torch.Size([5, 3, 8]))=
tensor([[[ 1.2396,  0.3921,  0.1825,  0.2751, -1.4760,  0.4640, -1.6733,
           0.6763],
         [ 1.9708,  1.4785,  0.1735, -1.1877,  0.2759, -1.2383,  0.5617,
           1.3385],
         [ 0.6429, -1.5699, -0.7098,  0.1701, -1.1864,  1.1818,  1.4489,
          -0.7856]],

        [[-0.6535,  0.6748,  0.7462, -0.0623, -0.8187, -1.2235, -0.9147,
          -0.9455],
         [ 1.2100, -0.3398, -0.3586,  0.9061,  0.2991, -1.7346,  0.3659,
           0.1648],
         [ 0.2576, -0.3584, -0.2585, -0.2607, -0.9804, -1.0118, -0.1088,
          -0.3156]],

        [[ 0.1399,  0.5173, -0.8558, -0.2992,  0.4754,  1.3691,  1.0444,
           0.8365],
         [-0.5918,  0.4880, -0.0514, -1.0572,  0.5755, -0.6108,  0.9089,
           0.5272],
         [-0.8563, -0.1981,  2.2380, -0.8900,  0.9122, -1.6969, -0.3610,
           0.7996]],

        [[ 0.1404, -0.0188,  0.6171,  0.0619,  0.3363,  1.1549, -2.7627,
          -0.3847],
         [ 0.8165,  1.4495,  0.1

In [37]:
layer_norm=LayerNormalization(inputs.size()[-1:])


In [38]:
out=layer_norm.forward(inputs)

y 
 : (torch.Size([5, 3, 8]))=
 tensor([[[ 1.2741,  0.3959,  0.1787,  0.2747, -1.5399,  0.4704, -1.7444,
           0.6904],
         [ 1.3993,  0.9547, -0.2241, -1.4537, -0.1316, -1.4993,  0.1265,
           0.8282],
         [ 0.7073, -1.3966, -0.5788,  0.2578, -1.0320,  1.2196,  1.4736,
          -0.6510]],

        [[-0.3562,  1.5076,  1.6078,  0.4733, -0.5880, -1.1560, -0.7227,
          -0.7659],
         [ 1.3509, -0.4762, -0.4983,  0.9927,  0.2770, -2.1206,  0.3558,
           0.1186],
         [ 1.5970,  0.0531,  0.3034,  0.2981, -1.5060, -1.5847,  0.6787,
           0.1603]],

        [[-0.3877,  0.1675, -1.8521, -1.0335,  0.1058,  1.4203,  0.9428,
           0.6369],
         [-0.9286,  0.7009, -0.1131, -1.6310,  0.8329, -0.9573,  1.3361,
           0.7601],
         [-0.7229, -0.1629,  1.9095, -0.7515,  0.7816, -1.4379, -0.3016,
           0.6858]],

        [[ 0.2265,  0.0807,  0.6630,  0.1546,  0.4059,  1.1555, -2.4319,
          -0.2543],
         [ 0.6361,  1.3999, -0.1