In [1]:
import numpy as np
import math

In [6]:
L,d_k,d_v=4,8,8
q=np.random.randn(L,d_k)
k=np.random.randn(L,d_k)
v=np.random.randn(L,d_v)

In [8]:
print("Q\n",q)
print("K\n",k)
print("V\n",v)

Q
 [[-0.29725018 -0.17409652 -0.37796023  0.21325724  0.3815085   1.48790813
   0.43688012  0.05565026]
 [ 1.08327293 -2.11086282 -0.29884714  1.38193404 -0.92846093 -0.36138767
   0.38922433 -1.35385075]
 [ 0.97586275  0.19866699 -0.56891277 -0.65697007  0.22307764 -0.94576992
   0.15882208 -0.19833581]
 [-0.02048442  0.67206763 -0.02016706  1.23347455 -1.97540837 -0.42170722
   0.42822197 -0.78822247]]
K
 [[-1.03348115 -1.38573026  0.57962195  0.91446585 -0.71150553 -0.78627456
  -0.66790129  0.53767363]
 [-1.11748591 -0.41222538 -0.68349949 -0.26533905  1.1313857  -0.04432358
   0.43246304  0.14210002]
 [ 0.69557191  0.33814537  1.64098152  0.53406348  0.75702974 -0.90331458
  -1.10662855  0.49424   ]
 [ 0.28216546 -0.92862296  1.71674926 -0.15785412  1.04715893 -0.34376946
   0.31852321  1.42376468]]
V
 [[-0.53815162 -0.78721363 -0.29006392  0.00255168 -0.94004942  1.72260867
  -0.31544045  0.60468867]
 [-0.24071203 -1.46755208  1.12249819 -1.52201328  0.53413412 -0.8238491
   0.59

In [9]:
np.matmul(q,k.T)

array([[-1.17882514,  1.16821629, -2.28315691, -0.49833821],
       [ 2.85291917, -1.56129671, -1.18892615, -1.11693171],
       [-1.84216921, -0.27442914,  0.2109436 , -0.45517755],
       [ 1.23342208, -2.71073054, -1.13929421, -3.76864937]])

In [10]:
#  NEEd of sqrt(d_k) in denominator:

q.var(),k.var(),np.matmul(q,k.T).var()

(0.716621957748681, 0.71785893613005, 2.4810221724622696)

In [11]:
scaled=np.matmul(q,k.T)/math.sqrt(d_k)
q.var(),k.var(),scaled.var()

(0.716621957748681, 0.71785893613005, 0.3101277715577836)

In [12]:
scaled

array([[-0.41677763,  0.41302683, -0.80721787, -0.17618916],
       [ 1.00865925, -0.55200175, -0.42034887, -0.39489499],
       [-0.65130517, -0.09702535,  0.07457983, -0.16092957],
       [ 0.43608056, -0.95838797, -0.40280133, -1.33241876]])

In [15]:
#Making
mask=np.tril(np.ones((L,L)))           

In [16]:
mask

array([[1., 0., 0., 0.],
       [1., 1., 0., 0.],
       [1., 1., 1., 0.],
       [1., 1., 1., 1.]])

In [17]:
mask[mask ==0]=-np.infty
mask[mask==1]=0

In [18]:
mask

array([[  0., -inf, -inf, -inf],
       [  0.,   0., -inf, -inf],
       [  0.,   0.,   0., -inf],
       [  0.,   0.,   0.,   0.]])

In [19]:
scaled+mask

array([[-0.41677763,        -inf,        -inf,        -inf],
       [ 1.00865925, -0.55200175,        -inf,        -inf],
       [-0.65130517, -0.09702535,  0.07457983,        -inf],
       [ 0.43608056, -0.95838797, -0.40280133, -1.33241876]])

In [20]:
#softmax

def softmax(x):
    return (np.exp(x).T/np.sum(np.exp(x),axis=-1)).T

In [21]:
attention=softmax(scaled+mask)

In [22]:
attention

array([[1.        , 0.        , 0.        , 0.        ],
       [0.82644818, 0.17355182, 0.        , 0.        ],
       [0.20801931, 0.36209649, 0.42988421, 0.        ],
       [0.54032234, 0.13398092, 0.2335238 , 0.09217294]])

In [23]:
new_v=np.matmul(attention,v)
new_v

array([[-5.38151623e-01, -7.87213629e-01, -2.90063923e-01,
         2.55167575e-03, -9.40049421e-01,  1.72260867e+00,
        -3.15440451e-01,  6.04688669e-01],
       [-4.86530441e-01, -9.05287605e-01, -4.49111980e-02,
        -2.62039347e-01, -6.84202186e-01,  1.28066630e+00,
        -1.57942243e-01,  4.97828571e-01],
       [ 2.88257038e-01, -1.06012782e+00,  3.07435216e-01,
        -4.47710381e-01,  4.57246443e-01, -6.37819591e-01,
         6.81057487e-01, -6.33058994e-01],
       [ 3.93591387e-02, -8.83313238e-01, -1.43634466e-03,
        -1.31796776e-01, -2.43139528e-01,  3.80270216e-01,
         1.98910372e-01,  1.11476017e-01]])

In [24]:
v

array([[-0.53815162, -0.78721363, -0.29006392,  0.00255168, -0.94004942,
         1.72260867, -0.31544045,  0.60468867],
       [-0.24071203, -1.46755208,  1.12249819, -1.52201328,  0.53413412,
        -0.8238491 ,  0.59205916, -0.01103577],
       [ 1.13370981, -0.84901172, -0.08997432,  0.23930742,  1.06862912,
        -1.62332688,  1.23822332, -1.75593772],
       [ 1.05928139, -0.68431916,  0.28109644,  0.16123225, -0.61106802,
        -0.66210564,  0.00944585,  2.12948678]])

In [25]:
def softmax(x):
     return (np.exp(x).T/np.sum(np.exp(x),axis=-1)).T

def scaled_dot_product_attention(q,k,v,mask=None):
    d_k=q.shape[-1]
    scaled=np.matmul(q,k.T)/math.sqrt(d_k)
    if mask is not None:
        scaled=scaled+mask
    attention=softmax(scaled)
    out=np.matmul(attention,v)
    return out,attention
    

In [27]:
values,attention=scaled_dot_product_attention(q,k,v,mask=None)
print("Q\n",q)
print("K\n",k)
print("V\n",v)
print("New V\n",values)
print("Attention\n",attention)


Q
 [[-0.29725018 -0.17409652 -0.37796023  0.21325724  0.3815085   1.48790813
   0.43688012  0.05565026]
 [ 1.08327293 -2.11086282 -0.29884714  1.38193404 -0.92846093 -0.36138767
   0.38922433 -1.35385075]
 [ 0.97586275  0.19866699 -0.56891277 -0.65697007  0.22307764 -0.94576992
   0.15882208 -0.19833581]
 [-0.02048442  0.67206763 -0.02016706  1.23347455 -1.97540837 -0.42170722
   0.42822197 -0.78822247]]
K
 [[-1.03348115 -1.38573026  0.57962195  0.91446585 -0.71150553 -0.78627456
  -0.66790129  0.53767363]
 [-1.11748591 -0.41222538 -0.68349949 -0.26533905  1.1313857  -0.04432358
   0.43246304  0.14210002]
 [ 0.69557191  0.33814537  1.64098152  0.53406348  0.75702974 -0.90331458
  -1.10662855  0.49424   ]
 [ 0.28216546 -0.92862296  1.71674926 -0.15785412  1.04715893 -0.34376946
   0.31852321  1.42376468]]
V
 [[-0.53815162 -0.78721363 -0.29006392  0.00255168 -0.94004942  1.72260867
  -0.31544045  0.60468867]
 [-0.24071203 -1.46755208  1.12249819 -1.52201328  0.53413412 -0.8238491
   0.59